### ISSUE TITLE
我下载项目下来导入报错，希望得到帮助

### ISSUE THREAD

**Issue by lifangzhen** [biezhi/elves#2]
是还没完成吗，好多错误

**Comment by MarchNineteen** [comment]
包冲突

**Comment by hellokaton** [comment]
# 运行这个项目需要安装 [lombok](https://projectlombok.org/) 插件，省去写 `Getter Setter` 了

**Comment by haoge320** [comment]
log 报错，怎么解决

**Comment by hellokaton** [comment]
@haoge320 
![image](https://user-images.githubusercontent.com/3849072/35324097-a582199a-012a-11e8-89b8-a4d529289ac5.png)
