### ISSUE TITLE
找不到log 错误

### ISSUE THREAD

**Issue by MarchNineteen** [biezhi/elves#5]
我说真的    添加了lomlock插件   代码里不报错了 但是运行的时候   还是会报 找不到log 错误
不知道是因为版本的问题还是 什么

**Comment by biezhi** [comment]
这个不会的，lombok 干的时候就是在编译时期帮你自动生成 Getter Setter，除此之外因为这个项目使用了 `slf4j-api` ，比如 [这里](https://github.com/biezhi/elves/blob/master/src/main/java/io/github/biezhi/elves/ElvesEngine.java#L28)，lombok 会自动添加一行

```java
private static final Logger log = LoggerFactory.getLogger(xxx.class);
```

**Comment by MarchNineteen** [comment]
这些我知道  我也一直很奇怪我可以截图给你看 

![image](https://user-images.githubusercontent.com/26375296/35379329-ab80a214-01f0-11e8-8e0b-e70dfe9a736d.png)
我怀疑是版本的问题

**Comment by biezhi** [comment]
![image](https://user-images.githubusercontent.com/3849072/35379375-e0f01240-01f0-11e8-8490-173f817c194b.png)
从这个截图可以看出 `lombok` 没有被成功安装，或者你安装后没有重新启动IDE。

**Comment by MarchNineteen** [comment]
![image](https://user-images.githubusercontent.com/26375296/35379458-1b0f2d94-01f1-11e8-897c-1338fc74740b.png)
![image](https://user-images.githubusercontent.com/26375296/35379480-27a116bc-01f1-11e8-913c-b597db4dde95.png)
也重启 了好几遍了 其他项目使用lomlock是可以的 我试过

**Comment by biezhi** [comment]
在终端下 `mvn clean compile` 然后重新导入试试

**Comment by MarchNineteen** [comment]
![image](https://user-images.githubusercontent.com/26375296/35379836-6c7c1844-01f2-11e8-8a2a-e2f2e87c001e.png)
终端compile 报错

**Comment by biezhi** [comment]
你本地 Java 的版本是多少？
